### ISSUE TITLE
Multi-steplib zis proposal

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zss#711]
As requested in https://github.com/zowe/zss/issues/703, this ticket is to discuss an implementation proposal

Goal: have `zwe components install -o /the/extension[.pax]` go beyond its current task of just copying unix content into the extensions directory, but also to update the ZIS STC steplib list.

# Idea 1
`zwe components install -o /the/extension[.pax] -d THE.DS1,THE.DS2`
... Have -d serve as a list of datasets to append to the steplib.

Problems: 
* `zwe components upgrade` and `zwe components uninstall` exist. How do we know which steplibs to REMOVE? How can we track which extension added which steplib entry? a file in the workspace directory? something in zowe.yaml?

* I don't like this being manual. How can we detect the datasets so that users do not need to be prompted, and cannot do something wrong? I'd like to query SMPE's knowledge somehow.

# Idea 2
No new -d parameter, just manifest info & SMPE lookup.
... How can I query what datasets on a system are associated with an FMID? I think that's superior. If a Zowe extension manifest could have a field for stating its FMID, like:

```yaml
name: angular-sample
id: org.zowe.zlux.sample.angular
version: 2.16.0
fmid: AZWE999
```

Then, can I get a list of datasets associated with it via something involving https://www.ibm.com/docs/en/zos/3.1.0?topic=command-listing-by-fmid-fmidset ?

And, if there were multiple datasets, how do I know which one goes in the steplib?
Would we need a suffix pattern to follow, such as:

```yaml
name: angular-sample
id: org.zowe.zlux.sample.angular
version: 2.16.0
fmid: AZWE999 # Proposed new attribute. Used with steplibLLQ to find exact dataset.
zisPlugins:
  - id: plugin1
    steplibLLQ: ZISPLUG1 # Proposed new pattern. No copy occurs, but steplib entry added
  - id: plugin2
    steplibLLQ: ZISPLUG2
  - id: plugin3
    path: "/zisServer" # Current zowe pattern. it copies from here to the zis plugin ds
```
